version: 2
jobs:
  lint:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: npm install
    - run: npm run lint

  deploy_staging:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: npm install
    - run: npm run build -- --mode development
    - run: sudo npm install -g firebase-tools
    - run: firebase use staging
    - run: firebase deploy --token "$FIREBASE_TOKEN"

  deploy_prod:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run: npm install
    - run: npm run build
    - run: sudo npm install -g firebase-tools
    - run: firebase use default
    - run: firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_deploy:
    jobs:
    - lint
    - deploy_staging:
        requires:
        - lint
        filters:
          branches:
            only: develop
    - deploy_prod:
        requires:
        - lint
        filters:
          branches:
            only: master
